### ISSUE TITLE
why get function always return DataLinkError: (Status 410)

### ISSUE THREAD

**Issue by ChandlerBBT** [Nasdaq/data-link-python#48]
![image](https://github.com/user-attachments/assets/9aee9869-5cfb-46be-8f6b-92d4ef95ef89)

however, I could get data by the `get_table` function, can't determine what's going on.

![image](https://github.com/user-attachments/assets/7cc7f255-8eaa-4857-bc37-1545751beb48)

**Comment by clientsuccessnasdaq** [comment]
-- Please reply above this line --


Dear Nasdaq/data-Link-Python,

Thank you for contacting the Nasdaq Data Client Success Team. 

Your email is very important to us. Urgent production issues will be
addressed as soon as possible during the hours of 4am to 6pm ET Monday
to Friday. General inquiries will be addressed within 1 to 2 business
days.

To efficiently support your request, please include relevant details
such as the data product/feed you are inquiring about.

Kind regards,
Nasdaq Data Client Success

 [1]


Links:
------
[1] https://www.nasdaq.com/

**Comment by Josuerinho** [comment]
Hi! I'm getting exactly the same problem. The `nasdaqdatalink.get()` function never worked no matter what I tried. I've tried to find the problem cause but couldn't figure it out. I've even changed my API key just in case. I created my account a day ago so not sure if this could be an issue with needing some time to fully activate it but in that case, I'd expect `nasdaqdatalink.get_table('ZACKS/FC', ticker='AAPL')` to not work either. So no idea...
![Screenshot 2024-09-29 at 3 51 57 PM](https://github.com/user-attachments/assets/9bda6f55-fd18-4686-8a19-17a67f695bdd)

**Comment by ChandlerBBT** [comment]
> Hi! I'm getting exactly the same problem. The `nasdaqdatalink.get()` function never worked no matter what I tried. I've tried to find the problem cause but couldn't figure it out. I've even changed my API key just in case. I created my account a day ago so not sure if this could be an issue with needing some time to fully activate it but in that case, I'd expect `nasdaqdatalink.get_table('ZACKS/FC', ticker='AAPL')` to not work either. So no idea... ![Screenshot 2024-09-29 at 3 51 57 PM](https://private-user-images.githubusercontent.com/44467032/371887486-9bda6f55-fd18-4686-8a19-17a67f695bdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NjY1NDYsIm5iZiI6MTcyNzY2NjI0NiwicGF0aCI6Ii80NDQ2NzAzMi8zNzE4ODc0ODYtOWJkYTZmNTUtZmQxOC00Njg2LThhMTktMTdhNjdmNjk1YmRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDAzMTcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3MmFlMDA3Y2I4NjRkMjgzYTRkOGU0MTc3MzU2NTJiODI3ZDQ0ZTg4NzM5NDU4NGY2ZGNjMTlhODZkMGZlOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7EjIZhJhJfypw8vYAyunhfYt2cqS50Z5rbAecCl8Tm4)

Thought it was just my bad luck, seems got a real problem somewhere.

**Comment by jhavens1566** [comment]
Also receiving this error, interestingly `get_table()` seems to work

Here's a stack trace:
```
>>> data = nasdaqdatalink.get('NSE/OIL')
Traceback (most recent call last):
  File "/home/johnathon/.local/lib/python3.10/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/johnathon/.local/lib/python3.10/site-packages/nasdaqdatalink/connection.py", line 90, in parse
    return response.json()
  File "/home/johnathon/.local/lib/python3.10/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/johnathon/.local/lib/python3.10/site-packages/nasdaqdatalink/get.py", line 48, in get
    data = Dataset(dataset_args['code']).data(params=kwargs, handle_column_not_found=True)
  File "/home/johnathon/.local/lib/python3.10/site-packages/nasdaqdatalink/model/dataset.py", line 47, in data
    return Data.all(**updated_options)
  File "/home/johnathon/.local/lib/python3.10/site-packages/nasdaqdatalink/operations/list.py", line 15, in all
    r = Connection.request('get', path, **options)
  File "/home/johnathon/.local/lib/python3.10/site-packages/nasdaqdatalink/connection.py", line 40, in request
    return cls.execute_request(http_verb, abs_url, **options)
  File "/home/johnathon/.local/lib/python3.10/site-packages/nasdaqdatalink/connection.py", line 52, in execute_request
    cls.handle_api_error(response)
  File "/home/johnathon/.local/lib/python3.10/site-packages/nasdaqdatalink/connection.py", line 96, in handle_api_error
    error_body = cls.parse(resp)
  File "/home/johnathon/.local/lib/python3.10/site-packages/nasdaqdatalink/connection.py", line 92, in parse
    raise DataLinkError(http_status=response.status_code, http_body=response.text)
nasdaqdatalink.errors.data_link_error.DataLinkError: (Status 410) Something went wrong. Please try again. If you continue to have problems, please contact us at connect@data.nasdaq.com.
```

**Comment by clientsuccessnasdaq** [comment]
-- Please reply above this line --


Dear Nasdaq/data-Link-Python,

Thank you for contacting the Nasdaq Data Client Success Team. 

Your email is very important to us. Urgent production issues will be
addressed as soon as possible during the hours of 4am to 6pm ET Monday
to Friday.

To efficiently support your request, please include relevant details
such as the data product/feed you are inquiring about.

Kind regards,
Nasdaq Data Client Success

 [1]


Links:
------
[1] https://www.nasdaq.com/

**Comment by clientsuccessnasdaq** [comment]
-- Please reply above this line --


            Hello,

Thank you for reaching out.

To help us look more closely into your inquiry, could you please send
us an email at ***@***.*** [1]? This will allow us to
assist you best.

Best regards,
Nasdaq Data Link


Links:
------
[1] ***@***.***

KIM LIRA
 Nasdaq Data Client Success 

  [1]

How would you rate my reply?
Great [2]    Okay [3]    Not Good [4]


Links:
------
[1] https://www.nasdaq.com/
[2]
https://secure.helpscout.net/satisfaction/740412352/record/8254906863/1/
[3]
https://secure.helpscout.net/satisfaction/740412352/record/8254906863/2/
[4]
https://secure.helpscout.net/satisfaction/740412352/record/8254906863/3/

**Comment by rwideman** [comment]
Getting the same here. nasdaqdatalink.get() fails but nasdaqdatalink.get_table() is successful.  Very frustrating as even the official documentation uses nasdaqdatalink.get().

**Comment by clientsuccessnasdaq** [comment]
-- Please reply above this line --


            Hello,

Thank you for reaching out.

To help us look more closely into your inquiry, could you please send
us an email at ***@***.*** [1]? This will allow us to
assist you best.

Best regards,
Nasdaq Data Link


Links:
------
[1] ***@***.***

KIM LIRA
 Nasdaq Data Client Success 

  [1]

How would you rate my reply?
Great [2]    Okay [3]    Not Good [4]


Links:
------
[1] https://www.nasdaq.com/
[2]
https://secure.helpscout.net/satisfaction/740919084/record/8261187458/1/
[3]
https://secure.helpscout.net/satisfaction/740919084/record/8261187458/2/
[4]
https://secure.helpscout.net/satisfaction/740919084/record/8261187458/3/
